name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "8 7,9,12,18,23 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: auto
        run: |
          git config --local user.email "aiyo3103198302@gmail.com"
          git config --local user.name "aiyo02"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
